// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:lukhu_packages_pkg/lukhu_packages_pkg.dart' show FirebaseOptions;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIy-2bH_nfutoW8X0Vn7DsUsvkyhJN2nU',
    appId: '1:257334306927:web:3f589c1434ad7216cb459a',
    messagingSenderId: '257334306927',
    projectId: 'lukhu-dev',
    authDomain: 'lukhu-dev.firebaseapp.com',
    storageBucket: 'lukhu-dev.appspot.com',
    measurementId: 'G-GBMEGCY8VV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPr-N51X3rR1IcBFUUXgvKWTS0zIzRviI',
    appId: '1:257334306927:android:af6dcee27d3bbefacb459a',
    messagingSenderId: '257334306927',
    projectId: 'lukhu-dev',
    storageBucket: 'lukhu-dev.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuuj4S-3BzjXrMkDaioMvD-JcRD3k4x2E',
    appId: '1:257334306927:ios:c99275de8a67fe3fcb459a',
    messagingSenderId: '257334306927',
    projectId: 'lukhu-dev',
    storageBucket: 'lukhu-dev.appspot.com',
    iosClientId: '257334306927-e3iafmv6i8etsfv87aoauuhl19r4hp78.apps.googleusercontent.com',
    iosBundleId: 'com.example.example',
  );
}
