name: Sales_pkg Linters

on: pull_request

jobs:
  style-lint:
   name: Run lints and tests
   runs-on: ubuntu-latest
   steps:
    - name: Set up SSH
      env:
        PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "$PRIVATE_KEY" > ~/.ssh/id_ed25519
        chmod 600 ~/.ssh/id_ed25519
        ssh-keyscan github.com >> ~/.ssh/known_hosts

    - uses: actions/checkout@v3
    - uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '12.x'
    - name: Install  Dart
      uses: dart-lang/setup-dart@v1
      with: 
        sdk: stable
    - name: Setup Flutter
      uses: subosito/flutter-action@v1
      with: 
       channel: "stable"
      #  version: "latest"
    - name: Configure git credentials
      run: |
        git config --global url."https://x-access-token:${{ secrets.GH_ACCESS_TOKEN }}@github.com/".insteadOf "https://github.com/"
    - run: flutter --version
    - run: flutter pub get
    - run: flutter test
    - run: flutter analyze